spring.application.name=api

# Connexion PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.105.159:5432/LaPoste
spring.datasource.username=chefpg
spring.datasource.password=mdpchefpg
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true